config/routes.rb
GoodTeacher::Application.routes.draw do

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :users do
    member do
      get :following, :followers
    end
    
    resources :comments

    resources :courses do
      resources :comments
      resources :favorites
    end
    resources :lessons do
      resources :comments
      resources :favorites
    end
    resources :units do
      resources :comments
      resources :favorites
      resources :lessons
      resources :assessments
      resources :vocabulary_lists
    end
    resources :assessments do
      resources :comments
      resources :favorites
    end
    resources :vocabulary_lists do
      resources :comments
      resources :favorites
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :books do
    resources :comments
    resources :favorites
  end

  
  match '/about', :to => 'static_pages#about'
  match '/privacypolicy', :to => 'static_pages#privacypolicy'

  root :to => 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @title = "Home"
    if current_user
      @courses = current_user.courses
      @units = current_user.units
      @user = current_user
    end
  end

  def about
    @title = "About Us"
  end

  def privacypolicy
    @title = "Privacy Policy"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_guesthome.html.erb
<div class="row">
  <div class="span8 offset1">
    <h1>GoodTeacher</h1>
    <p>Welcome to the Jungle! Please create an account!</p>
  </div>
</div>

app/views/static_pages/_userhome.html.erb
<h1>Welcome Back <%= current_user.name %>! </h1>

<div class="row">
  <div class="span10">
    <%= render 'shared/stats' %>
    <%# link_to "Your Courses", user_courses_path(current_user) %>

    <%# unless current_user.courses.blank? %>
      <%# render 'shared/courses' %>
    <%# end %>
    <%# link_to "Create Course", new_user_course_path(current_user) %>

    <legend><%= link_to "Unit Gallery", user_units_path(current_user) %></legend>

    <% unless current_user.units.blank? %>
      <%= render 'shared/units' %>
    <% end %>
    <%= link_to "Create Unit", new_user_unit_path(current_user) %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% if current_user %>
  <%= render 'userhome' %>
<% else %>
  <%= render 'guesthome' %>
<% end %>

app/views/static_pages/privacypolicy.html.erb
<h1>StaticPages#home</h1>
Find me in app/views/static_pages/home.html.erb