config/routes.rb
GoodTeacher::Application.routes.draw do

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :users do
    member do
      get :following, :followers
    end
    
    resources :comments

    resources :courses do
      resources :comments
      resources :favorites
    end
    resources :lessons do
      resources :comments
      resources :favorites
    end
    resources :units do
      resources :comments
      resources :favorites
      resources :lessons
      resources :assessments
      resources :vocabulary_lists
    end
    resources :assessments do
      resources :comments
      resources :favorites
    end
    resources :vocabulary_lists do
      resources :comments
      resources :favorites
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :books do
    resources :comments
    resources :favorites
  end

  
  match '/about', :to => 'static_pages#about'
  match '/privacypolicy', :to => 'static_pages#privacypolicy'

  root :to => 'static_pages#home'

end

app/views/shared/_assessments.html.erb
<% for assessment in @assessments %>
  <ul id="<%= assessment.id %>">
    <strong><%= link_to assessment.name, user_assessment_path(@user, assessment) %></strong> - <%= assessment.description %>
    <%= assessment.prompt %>
  </ul>
<% end %>

app/views/shared/_courses.html.erb
<% for course in @courses %>
  <ul id="<%= course.id %>">
    <%= link_to course.name, user_course_path(@user, course) %>
    Created <%= distance_of_time_in_words(course.created_at, Time.now) %> ago <br />
    <%= course.description %>
  </ul>
<% end %>

app/views/shared/_error_messages.erb
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

app/views/shared/_lessons.html.erb
<% @lessons.each do |lesson| %>
  <ul>
    <strong><%= link_to lesson.name, user_lesson_path(@user, lesson) %></strong> - <%= lesson.description %>
    <%= lesson.description %>
  </ul>
<% end %>

app/views/shared/_side_bar.html.erb
  <aside class="span3">
    <%= render 'shared/stats' %>
    <section>
      <%= render 'favorites/favorite_form' if signed_in? %>
    </section>
  </aside>
</div>
<div class="row">
  <div class="span6">
    <legend>Comments</legend>
    <%= render "comments/comments" %>
    <%= render "comments/form" %>
  </div>
</div>

app/views/shared/_side_show.html.erb
  <aside class="span3">
    <%= render 'shared/stats' %>
    <section>
      <%= render 'favorites/favorite_form' if signed_in? %>
    </section>
  </aside>
</div>
<div class="row">
  <div class="span6">
    <legend>Comments</legend>
    <%= render "comments/comments" %>
    <%= render "comments/form" %>
  </div>
</div>

app/views/shared/_stats.html.erb
<section>
  <% unless @user.avatar_url.nil? %><%= image_tag @user.avatar_url(:display) %><br /><% end %>
  <legend><%= link_to @user.name, user_path(@user) %></legend>
  <strong>School:</strong> <%= @user.school %><br />
  <strong>Location:</strong> <%= @user.location %>
</section>
<section>
  <div class="stats">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">
        <%= @user.followed_users.count %>
      </strong>following
    </a>
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>followers
    </a>
  </div>
</section>

app/views/shared/_units.html.erb
<% @units.each do |unit| %>
  <ul>
    <%= link_to unit.name, user_unit_path(@user, unit) %>
    Created <%= distance_of_time_in_words(unit.created_at, Time.now) %> ago <br />
    <%= unit.description %>
  </ul>
<% end %>

app/views/shared/_vocabulary_lists.html.erb
<% @vocabulary_lists.each do |vocabulary_list| %>
  <ul>
    <strong><%= link_to vocabulary_list.name, user_vocabulary_list_path(@user, vocabulary_list) %></strong> - <%= vocabulary_list.description %>
  </ul>
<% end %>