config/routes.rb
GoodTeacher::Application.routes.draw do

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :users do
    member do
      get :following, :followers
    end
    
    resources :comments

    resources :courses do
      resources :comments
      resources :favorites
    end
    resources :lessons do
      resources :comments
      resources :favorites
    end
    resources :units do
      resources :comments
      resources :favorites
      resources :lessons
      resources :assessments
      resources :vocabulary_lists
    end
    resources :assessments do
      resources :comments
      resources :favorites
    end
    resources :vocabulary_lists do
      resources :comments
      resources :favorites
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :books do
    resources :comments
    resources :favorites
  end

  
  match '/about', :to => 'static_pages#about'
  match '/privacypolicy', :to => 'static_pages#privacypolicy'

  root :to => 'static_pages#home'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  extend FriendlyId
  
  belongs_to :user

  has_many :comments, :as => :commentable
  has_many :favorites, :as => :favorable
  has_many :lessons_unitss, :foreign_key => "lesson_id",
                        :dependent => :destroy
  has_many :units, :through => :lessons_unitss

  attr_accessible :body, :name, :description, :user_id

  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @lessons = @user.lessons.paginate(page: params[:page])
    @title = "My Lessons"
  end
  

  def show
    @user = User.find(params[:user_id])
    @lesson = @user.lessons.find(params[:id])
    @title = @lesson.name
    @commentable = Lesson.find(params[:id])
    @comments = @commentable.comments
    @comment = Comment.new
    @favorable = @lesson
    if @lesson.favorites.where(favorer: current_user).first
      @favorite = @lesson.favorites.where(favorer: current_user).first
    else
      @favorite = Favorite.new
    end
  end

  def new
    @title = "New Lesson"
    @user = User.find(params[:user_id])
    @unit = @user.units.find(params[:unit_id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_lessons_path(@user)
    end
    @lesson = @unit.lessons.build
  end

  def create
    @user = User.find(params[:user_id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_lessons_path(@user)
    else
      @unit = @user.units.find(params[:unit_id])
      @lesson = Lesson.new(params[:lesson])
      @lesson.user_id = current_user.id
      @unit.lessons << @lesson
      @unit.save
      if @unit.save
        redirect_to user_lesson_path(@user, @lesson), notice: "Successfully created lesson."
      else
        render :action => :new
      end
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @lesson = @user.lessons.find(params[:id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_lesson_path(@user, @lesson)
    end
  end

  def update
    @user = User.find(params[:user_id])
    @lesson = @user.lessons.find(params[:id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_lesson_path(@user, @lesson)
    else
      if @lesson.update_attributes(params[:lesson])
        redirect_to user_lesson_path(@user, @lesson), notice: "Successfully updated lesson."
      else
        render :edit
      end
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @lesson = current_user.lesson.find(params[:id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_lesson_path(@user, @lesson)
    else
      @lesson.destroy
      redirect_to lessons_url, notice: "Successfully destroyed lesson"
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= semantic_form_for [@user, @unit, @lesson] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>
    
  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit "Save", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/lessons/edit.html.erb
<div class="row">
  <div class="span6 offset2">
      <%= render 'form' %>
  </div>
</div>

app/views/lessons/index.html.erb
<legend><%= @title %></legend>

<%= will_paginate @lessons %>

<%= render 'shared/lessons' %>

<%= will_paginate @lessons %>

<% if current_user == @user %>
  <%= link_to "New Lesson", new_user_lesson_path(@user) %>
<% end %>

app/views/lessons/new.html.erb
<div class="row">
  <div class="span6">
    <%= render 'form' %>
  </div>
</div>

app/views/lessons/show.html.erb
<div class="row">
  <div class="span8">
    <legend><%= @lesson.name %></legend>
    <%= @lesson.description %>
    <% if current_user == @user %>
      <%= link_to "Edit", edit_user_lesson_path(@user, @lesson) %>
    <% end %>
    <hr />
    <section>
      <%= @lesson.body %>
    </section>
  </div>
  <%= render 'shared/side_bar' %>