config/routes.rb
GoodTeacher::Application.routes.draw do

  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
  end

  resources :users do
    member do
      get :following, :followers
    end
    
    resources :comments

    resources :courses do
      resources :comments
      resources :favorites
    end
    resources :lessons do
      resources :comments
      resources :favorites
    end
    resources :units do
      resources :comments
      resources :favorites
      resources :lessons
      resources :assessments
      resources :vocabulary_lists
    end
    resources :assessments do
      resources :comments
      resources :favorites
    end
    resources :vocabulary_lists do
      resources :comments
      resources :favorites
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :books do
    resources :comments
    resources :favorites
  end

  
  match '/about', :to => 'static_pages#about'
  match '/privacypolicy', :to => 'static_pages#privacypolicy'

  root :to => 'static_pages#home'

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  has_many :comments, :as => :commentable
  has_many :favorites, :as => :favorable
  has_many :unit_links, :foreign_key => "unit_id",
                        :dependent => :destroy
  has_many :courses, :through => :unit_links
  has_many :lessons_unitss, :foreign_key => "unit_id",
                        :dependent => :destroy
  has_many :lessons, :through => :lessons_unitss
  has_many :assessments_units, :foreign_key => "unit_id",
                        :dependent => :destroy
  has_many :assessments, :through => :assessments_units
  has_many :vocabulary_lists_units, :foreign_key => "unit_id",
                        :dependent => :destroy
  has_many :vocabulary_lists, :through => :vocabulary_lists_units

  attr_accessible :description, :name

  validates :name, :presence => true, 
                   :length => { :minimum => 2 },
                   :length => { :maximum => 150 },
                   :on => :update

  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  respond_to :html

  def index
    @user = User.find(params[:user_id])
    @title = "My units"
    @units = @user.units.paginate(page: params[:page])
  end
  

  def show
    @user = User.find(params[:user_id])
    @unit = Unit.find(params[:id])
    @title = @unit.name
    @commentable = @unit
    @comments = @commentable.comments
    @comment = Comment.new
    @favorable = @unit
    if @unit.favorites.where(favorer: current_user).first
      @favorite = @unit.favorites.where(favorer: current_user).first
    else
      @favorite = Favorite.new
    end

    @lesson = Lesson.new
    @lessons = @unit.lessons.paginate(page: params[:page]).per_page(5)
    @assessment = Assessment.new
    @assessments = @unit.assessments.paginate(page: params[:page]).per_page(5)
    @vocabulary_list = VocabularyList.new
    @vocabulary_lists = @unit.vocabulary_lists.paginate(page: params[:page]).per_page(5)
  end

  def new
    @user = User.find(params[:user_id])
    @title = "New unit"
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_units_path(@user)
    end
    @unit = current_user.units.new
  end

  def create
    @user = User.find(params[:user_id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_units_path(@user)
    else
      @unit = current_user.units.new(params[:unit])
      if @unit.save
        redirect_to user_unit_path(@user, @unit), notice: "Successfully created unit."
      else
        render :new
      end
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @unit = Unit.find(params[:id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_unit_path(@user, @unit)
    end
  end

  def update
    @user = User.find(params[:user_id])
    @unit = Unit.find(params[:id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_unit_path(@user, @unit)
    else
      if @unit.update_attributes(params[:unit])
        redirect_to user_unit_path(@user, @unit), notice: "Successfully updated unit."
      else
        render :edit
      end
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @unit = current_user.unit.find(params[:id])
    if current_user.nil? || current_user.id != @user.id
      redirect_to user_unit_path(@user, @unit)
    else
      @unit.destroy
      redirect_to user_units_path(@user), notice: "Successfully destroyed unit"
    end
  end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for [@user, @unit] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>
  
  <%= f.submit "Save", :class => "btn btn-large btn-primary" %></p>
<% end %>

app/views/units/edit.html.erb
<div class="row">
  <div class="span6 offset2">
    <%= render 'form' %>
  </div>
</div>

app/views/units/index.html.erb
<legend><%= @title %></legend>

<%= will_paginate @assessments %>

<%= render 'shared/units' %>

<%= will_paginate @assessments %>

<% if current_user == @user %>
  <%= link_to "New Unit", new_user_unit_path %>
<% end %>

app/views/units/new.html.erb
<div class="row">
  <div class="span6">
    <%= render 'form' %>
  </div>
</div>

app/views/units/show.html.erb
<div class="row">
  <div class="span8">
    <legend><%= @unit.name %></legend>
    <%= @unit.description %>
    <% if current_user == @user %>
      <%= link_to "Edit", edit_user_unit_path(@user, @unit) %>
    <% end %>
    
    <% if @lessons.any? || current_user == @user %>
      <legend>Content</legend>
      <h2>Lessons</h1>
      <%= render "shared/lessons" %>
      <%= will_paginate @lessons %>
      <% if current_user == @user %>
        <%= link_to "Add a Lesson", new_user_unit_lesson_path(@user, @unit) %>
      <% end %>
    <% end %>

    <% if @assessments.any? || current_user == @user %>
      <h2>Assessments</h2>
      <%= render "shared/assessments" %>
      <%= will_paginate @assessments %>
      <% if current_user == @user %>
        <%= link_to "Add an Assessment", new_user_unit_assessment_path(@user, @unit) %>
      <% end %>
    <% end %>

    <% if @vocabulary_lists.any? || current_user == @user %>
      <h2>Terms Lists</h2>
      <%= render "shared/vocabulary_lists" %>
      <%= will_paginate @vocabulary_lists %>
      <% if current_user == @user %>
        <%= link_to "Add a Vocabulary List", new_user_unit_vocabulary_list_path(@user, @unit) %>
      <% end %>
    <% end %>
    <h2>Documents</h2>
    <%= link_to "Add a Document" %>
  </div>
  <%= render 'shared/side_bar' %>